// Autogenerated by Laurette ( https://github.com/KittyMac/laurette )

using System.Collections.Generic;

// Laurette was not provided with any valid .strings files; please ensure your
// project contains .strings files in the correct format and try again


public struct Localizations {
	public static string GetLanguageCode() { return null; }

	public static string TranslateKey(string key) {
		return null;
	}
}
